<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
 
class pdf {
    
    function pdf()
    {
        $CI = & get_instance();
        log_message('Debug', 'mPDF class is loaded.');
    }
 
    function load($param=NULL)
    {
        include_once APPPATH.'/third_party/mpdf/mpdf.php';
         
        if ($params == NULL)
        {
            $param = '"en-GB-x","A4","","",10,10,10,10,6,3';         
        }
         
        return new mPDF($param);
    }
}


/* End of file pdf.php */
/* Location: ./application/libraries/pdf.php */
/* Please DO NOT modify this information : */
<<<<<<< HEAD
/* Generated by Harviacode Codeigniter CRUD Generator 2024-06-13 05:21:47 */
=======
/* Generated by Harviacode Codeigniter CRUD Generator 2024-06-03 06:33:33 */
>>>>>>> 985fb331d309cc195f7522724352eb5afd8d9c3d
/* http://harviacode.com */