<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Surat_master_model extends CI_Model
{

    public $table = 'surat_master';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    //kirim ke form surat
    public function get_header()
    {
        $query = $this->db->select('*')->limit(1)->get('header_surat')->row_array();
        return $query;
    }

     // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // tampilkan surat dilayanan penduduk
    function get_surat_master()
    {
        $query ="SELECT * FROM `surat_master` WHERE `tampil_surat` = 1 ORDER BY `id` DESC";
        return $this->db->query($query)->result_array();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function ApiDaftarSurat()
    {
        $query ="SELECT * FROM `surat_master` WHERE `active` = 1 ORDER BY `id` DESC";
        return $this->db->query($query)->result_array();
    }

    function updateSuratById($id)
    {
        $nama           = $this->input->post('nama');
        $url            = $this->input->post('url');
        $singkatan      = $this->input->post('singkatan');
        $tampil_surat   = $this->input->post('tampil_surat');

        $data = [
            'nama'          => $nama,
            'url'           => $url,
            'singkatan'     => $singkatan,
            'tampil_surat'  => $tampil_surat,
        ];

        $this->db->where('id', $this->input->post('id'));
        $this->db->update('surat_master', $data);
    }

    function lock_surat($id = '', $val = 0)
    {
        $sql = "UPDATE surat_master SET active = ? WHERE id = ?";
        $hasil = $this->db->query($sql, array($val, $id));
        $this->session->success = ($hasil === TRUE ? 1 : -1);
    }

    function hapusSuratById($where,$table)
    {
        $this->db->where($where);
        $this->db->delete($table);
    }

    function get_syarat_id($id)
    {
        $this->db->where('id_surat', $id);
        return $this->db->get('syarat_surat')->result_array();
    }

    public function update_syarat_surat($surat_format_id = FALSE, $syarat_surat)
    {
        if (empty($surat_format_id))
        {
            return FALSE;
        }

        $this->hapus_syarat($surat_format_id);

        // Tambahkan syarat baru yg dipilih
        foreach ($syarat_surat as $syarat)
        {
            $data = array('id_surat' => $surat_format_id, 'id_syarat' => $syarat);
            $result = $this->db->insert('syarat_surat', $data);
        }

    }

    private function hapus_syarat($id = 0)
    {
        // Hapus semua syarat surat berdasarkan surat_format_id
        $this->db
            ->where('id_surat', $id)
            ->delete('syarat_surat');
    }

    // update data
    function update_header($id, $data)
    {
        $this->db->where('id', $id);
        $this->db->update('header_surat', $data);
    }

    //get nomor urut surat akhir
    function nomor_surat_akhir($id)
    {
        $query = "SELECT * FROM log_surat WHERE id_surat=$id ORDER BY no_surat DESC LIMIT 1";
        $result = $this->db->query($query)->row();
        return $result;
    }

    //get nomor urut surat otomatis
    function nomor_urut_surat($id)
    {
        $this->db->select('RIGHT(log_surat.no_surat, 1) as kode', FALSE);
        $this->db->where('id_surat', $id);
        $this->db->order_by('no_surat','DESC');    
        $this->db->limit(1);    
        $query = $this->db->get('log_surat');      
          if($query->num_rows() <> 0){      
           //jika kode ternyata sudah ada.      
           $data = $query->row();      
           $kode = intval($data->kode) + 1;    
          }
          else {      
           //jika kode belum ada      
           $kode = 1;    
          }

        $kodemax = str_pad($kode, STR_PAD_LEFT); 
        $kodejadi = $kodemax; 
        return $kodejadi; 
    }

    //daftar persyaratan surat tampilkan dilayanan penduduk
    function get_daftar_persyaratan($id)
    {
        $sql = "SELECT s.*, dp.nama as nama_syarat
        FROM syarat_surat s 
        LEFT JOIN daftar_persyaratan dp ON s.id_syarat = dp.id
        WHERE id_surat=$id
        ORDER BY s.id ASC";
        $result = $this->db->query($sql)->result();
        return $result;
    }

}

/* End of file Surat_master_model.php */
/* Location: ./application/models/Surat_master_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-11-07 04:25:49 */
/* http://harviacode.com */