<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Text_berjalan_model extends CI_Model
{

    public $table = 'text_berjalan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
    	$this->db->or_like('isi', $q);
    	$this->db->or_like('tautan_artikel', $q);
    	$this->db->or_like('judul_tautan', $q);
    	$this->db->or_like('status', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    	$this->db->or_like('isi', $q);
    	$this->db->or_like('tautan_artikel', $q);
    	$this->db->or_like('judul_tautan', $q);
    	$this->db->or_like('status', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function Delete_all($id)
    {
        $this->db->where_in('id', $id);
        $this->db->delete($this->table);
    }

    function lock_status($id = '', $val = 0)
    {
        $sql = "UPDATE text_berjalan SET status = ? WHERE id = ?";
        $hasil = $this->db->query($sql, array($val, $id));
        $this->session->success = ($hasil === TRUE ? 1 : -1);
    }

}

/* End of file Text_berjalan_model.php */
/* Location: ./application/models/Text_berjalan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-09-26 12:52:02 */
/* http://harviacode.com */