<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Umkm_model extends CI_Model
{

    public $table = 'umkm';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('no_tlp', $q);
	$this->db->or_like('nama_usaha', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('latitude', $q);
	$this->db->or_like('longitude', $q);
	$this->db->or_like('tgl_posting', $q);
	$this->db->or_like('gambar', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('no_tlp', $q);
	$this->db->or_like('nama_usaha', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('latitude', $q);
	$this->db->or_like('longitude', $q);
	$this->db->or_like('tgl_posting', $q);
	$this->db->or_like('gambar', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function updateKategoriById($id)
    {
        $kat = $this->input->post('nama');

        $data = [
            'nama' => $kat
        ];

        $this->db->where('id', $this->input->post('id'));
        $this->db->update('kategori_umkm', $data);
    }

    function hapus_data_kat($where,$table)
    {
        $this->db->where($where);
        $this->db->delete($table);
    }
}

/* End of file Umkm_model.php */
/* Location: ./application/models/Umkm_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-07-22 07:55:29 */
/* http://harviacode.com */